version: "3"
services:
  # API
  api-user:
    build:
      context: .
      dockerfile: api-user/api-user.Dockerfile
    image: lky/api-user
    ports:
      - "80:8000"

  api-auction:
    build:
      context: .
      dockerfile: api-auction/api-auction.Dockerfile
    image: lky/api-auction
    ports:
      - "7000:7000"
